### ISSUE TITLE
XMP backends: Issue with GExiv2

### ISSUE THREAD

**Issue by rmast** [FriedrichFroebel/didjvu#5]
Hi, I see you made two out of three xmp-backends work with the tests.

I'm now investigating the gexiv2/exiv2-issue. The most close to the finding is this one:

https://github.com/msys2/MINGW-packages/issues/7167

I think the solution would be to hack something in for Ubuntu at this spot:
https://gitlab.gnome.org/GNOME/gexiv2/-/commit/f72dc06ecfedabb6bbd75dc538fd342b59325b26

The issue seems solved for Windows with two different compile options: EXV_UNICODE_PATH or G_OS_WIN32.

I think there should be a compile option for getting it to work on Ubuntu as well. There are discussions about getting it in a stream instead and that seems to be a hard path to follow, so no easy road.

**Comment by rmast** [comment]
Or this might be an issue: "On Ubuntu GExiv2.Metadata.open_path() does not return boolean"
https://github.com/fszymanski/caja-extensions/commit/c6ece8a5a6eee40aecad4ec0b69fcb7d83bf5b5c

**Comment by rmast** [comment]
I have just copied the solution from my last post above. All tests return Ok now. Can you see whether the tests are still valid?
https://github.com/rmast/didjvu/commit/9d61fd86a258d1d5e7e66c291343ac0402852c3c

**Comment by FriedrichFroebel** [comment]
When I run the tests on Ubuntu 20.04 with Python 3.8 (packages installed from official repos, Python inside a virtual environment with `vext.gi` for the introspections to work), all were fine. This especially holds true for all three XMP backends, as I apparently had to fix some GExiv2 issues for them to pass.

I am not getting the real difference from your proposed change to my solution when simply removing the `assert`. Do we really need `GExiv2.Metadata.new()` instead of `GExiv2.Metadata()` or does this fail in your setup? Additionally I do not understand why we should wrap the load call into your exception handling. With

```python3
            try:
                self._meta.open_path(fp.name)
            except GLib.Error:
                assert_true(false,"GLib.Error")
```

you will just convert a maybe useful *GLib.Error* error message into a useless `AssertionError("Glib.Error")`.

If everything is still valid with my changes is something I cannot tell, because most of the stuff is not in my area of expertise. I just tried to fix the code for the existing tests to pass, assuming that they cover the relevant stuff - with the intent to make this tool I use regularly usable to everyone who is not able to use the Python 2 version (to be honest, I still use the original Python 2 version most of the time for now, but on a different system and with nearly none of the advanced features).

**Comment by rmast** [comment]
Please feel free to experiment. If you just remove the assert then that's probably also fine. I didn't play with those variations.

I don't know how many users didjvu has, but I would think somehow putting out a new version for test would make possible to find out. I think @jsbien knows how to alert package maintainers.

**Comment by jsbien** [comment]
@rmast As for Debian, just posting a follow-up to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=994118 seems sufficient.

**Comment by FriedrichFroebel** [comment]
@rmast I have removed the assertion.

Regarding a new release or packaging, there are two things which should be sorted out:

* Gamera 4 is still available as a pre-release only, making https://github.com/FriedrichFroebel/didjvu/blob/e82896c1e27c1aee5b6aab40a05c9b0b1ec4fa43/lib/gamera_support.py#L54-L55 or some other modification necessary.
* While I have been able to fix the `utils.enhance_import` functionality lately, my comment regarding the argument parsing in https://github.com/jwilk/didjvu/issues/13#issuecomment-918048197 should still hold true, although I have not tested this lately:

  > `didjvu.lib.cli.ArgumentParser.parse_args` does not work as before and seems to require additional handling for the missing `fg_bg_defaults` attribute if no parameters are set.

**Comment by rmast** [comment]
If you intent to put effort in the arguments, I saw something has changed on arguments with Python3.9, it might have some improvements.


Outlook voor Android downloaden<https://aka.ms/ghei36>
________________________________

**Comment by FriedrichFroebel** [comment]
Each Python version will have its own improvements for the *stdlib* modules, so this is nothing surprising. Nevertheless I could not really reproduce an issue as I do not remember what appeared to be broken back then, so this might be no actual issue.

**Comment by rmast** [comment]
> * Gamera 4 is still available as a pre-release only, making https://github.com/FriedrichFroebel/didjvu/blob/e82896c1e27c1aee5b6aab40a05c9b0b1ec4fa43/lib/gamera_support.py#L54-L55
>    or some other modification necessary.

@cdalitz suggests to release a releasenumber:
https://github.com/hsnr-gamera/gamera-4/discussions/40

**Comment by cdalitz** [comment]
Gamera 4.0.0 is now properly released:
[https://github.com/hsnr-gamera/gamera-4/releases/tag/v4.0.0](https://github.com/hsnr-gamera/gamera-4/releases/tag/v4.0.0)
